# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-15 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='sale',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='img_url',
            field=models.CharField(max_length=500),
        ),
    ]
